repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: &exclude_pre_commit_hooks >
      (?x)^(
        tests/.*(?<!\.py)$|
      )$
  - id: fix-encoding-pragma
    args: [--remove]
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
    exclude: *exclude_pre_commit_hooks

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.30.0
  hooks:
  - id: check-github-workflows

- repo: https://github.com/ikamensh/flynt/
  rev: 1.0.1
  hooks:
  - id: flynt
    args: [--line-length=120, --fail-on-change]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: >-
      (?x)^(
        tests/.*|
        environment.yml|
      )$

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.6
  hooks:
    # Check and update the uv lockfile
  - id: uv-lock

- repo: local

  hooks:

  - id: mypy
    name: mypy
    entry: mypy
    args: [--config-file=pyproject.toml, --pretty]
    language: python
    types: [python]
    require_serial: true
    pass_filenames: true
    exclude: >-
      (?x)^(
        .github/.*|
        .molecule/.*|
        docs/.*|
        tests/.*|
      )$

  # - id: generate-conda-environment
  #   name: Update conda environment file
  #   entry: python ./utils/dependency_management.py generate-environment-yml
  #   language: system
  #   pass_filenames: false
  #   files: >-
  #     (?x)^(
  #       pyproject.toml|
  #       utils/dependency_management.py|
  #       environment.yml|
  #     )$
  #
  # - id: validate-conda-environment
  #   name: Validate environment.yml
  #   entry: python ./utils/dependency_management.py validate-environment-yml
  #   language: system
  #   pass_filenames: false
  #   files: >-
  #     (?x)^(
  #       pyproject.toml|
  #       utils/dependency_management.py|
  #       environment.yml|
  #     )$
  #
  # - id: verdi-autodocs
  #   name: Automatically generating verdi docs
  #   entry: python ./utils/validate_consistency.py verdi-autodocs
  #   language: system
  #   pass_filenames: false
  #   files: >-
  #     (?x)^(
  #       src/aiida/cmdline/commands/.*|
  #       src/aiida/cmdline/params/.*|
  #       src/aiida/cmdline/params/types/.*|
  #       utils/validate_consistency.py|
  #     )$



# WG below
# repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#         exclude: \.svg$
#     -   id: trailing-whitespace
# -   repo: https://github.com/pycqa/flake8
#     rev: '6.0.0'
#     hooks:
#     -   id: flake8
#         args: ['--max-line-length=121', '--ignore=F821, F722, E203, W503']
#         exclude: ^docs/gallery/
#
# -   repo: https://github.com/psf/black
#     rev: 22.3.0
#     hooks:
#     -   id: black
