name: Install aiida-workgraph
description: Install aiida-workgraph package and its Python dependencies

inputs:
  python-version:
    description: Python version
    default: '3.9'              # Lowest supported version
    required: false
  extras:
    description: list of optional dependencies
    # NOTE: The default 'pre-commit' extra recursively contains
    # other extras needed to run the tests.
    default: pre-commit
    required: false

runs:
  using: composite
  steps:
  - name: Set Up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}

  - name: Set up uv
    uses: astral-sh/setup-uv@v6
    with:
      version: 0.8.17
      python-version: ${{ inputs.python-version }}
      activate-environment: true

  - name: Install dependencies from uv lock
    # NOTE: We're asserting that the lockfile is up to date
    run: uv sync --locked ${{ inputs.extras && format('--extra {0}', inputs.extras) || '' }}
    shell: bash
