name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.12']
        aiida-core-version: ['2.6', '2.7']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
      rabbitmq:
        image: rabbitmq:latest
        ports:
        - 5672:5672

    steps:
    - uses: actions/checkout@v5

    - name: Install aiida-workgraph
      uses: ./.github/actions/install-aiida-workgraph
      with:
        python-version: ${{ matrix.python-version }}
        extras: widget,pre-commit,tests
        from-lock: 'false'  # Use false to allow version override

    - name: Override aiida-core version
      run: uv pip install aiida-core==${{ matrix.aiida-core-version }}

    - name: Install additional dependencies
      run: |
        uv pip install pytest-xdist
        playwright install
        uv pip list

    - name: Install system dependencies
      run: sudo apt update && sudo apt install --no-install-recommends graphviz

    - name: Create AiiDA profile
      run: verdi setup -n --config .github/config/profile.yaml

    - name: Run pytest
      env:
        AIIDA_WARN_v3: 1
      run: pytest -n auto -v --cov --durations=0

    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.10' && github.repository == 'aiidateam/aiida-workgraph'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: aiida-workgraph-py3.10
        files: ./coverage.xml
        fail_ci_if_error: false
