name: ci

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.12']
        aiida-core-version: ['2.6', '2.7']

    steps:
    - uses: actions/checkout@v5

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: 0.7.6
        python-version: ${{ matrix.python-version }}
        activate-environment: true

    - name: Install aiida-workgraph in development mode
      run: |
        uv pip install -e .[widget,pre-commit,tests]
        uv pip list

    - name: Override aiida-core version
      run: uv pip install aiida-core==${{ matrix.aiida-core-version }}

    - name: Install additional dependencies
      run: |
        uv pip install pytest-xdist
        playwright install

    - name: Install system dependencies
      run: sudo apt update && sudo apt install --no-install-recommends graphviz

    - name: Create AiiDA profile
      run: verdi presto --profile-name ci-tests

    - name: Run pytest
      env:
        AIIDA_WARN_v3: 1
      run: pytest -n auto -v --cov --durations=0

    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.9' && github.repository == 'aiidateam/aiida-workgraph'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: aiida-workgraph-py3.9
        files: ./coverage.xml
        fail_ci_if_error: false
