name: pre-commit

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]

env:
  FORCE_COLOR: 1

jobs:

  pre-commit:

    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Install python dependencies
      uses: ./.github/actions/install-aiida-workgraph
      with:
        python-version: '3.10'
        from-lock: 'true'

    - name: Run pre-commit
      run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
